#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/tom/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# conky &
xfce4-power-manager &
gkrellm &
nm-applet &
# fbsetbg /home/tom/Picasa/Collages/2011-5-6.jpg &
fbsetbg -a -r /home/tom/Dropbox/Private-Photos/2011-8-22\ Dump/First\ Day\ of\ Kindergarten\!
xscreensaver &
dropbox start &
xfce4-terminal &
gnome-do &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/tom/.fluxbox/log"
